services:
    nicob.scrum.backlog.manager.default: 
        class: NicoB\ScrumBundle\Manager\BacklogManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.backlog.class%]

    nicob.scrum.project.manager.default:
        class: NicoB\ScrumBundle\Manager\ProjectManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.project.class%]

    nicob.scrum.sandbox.manager.default:
        class: NicoB\ScrumBundle\Manager\SandboxManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.sandbox.class%]

    nicob.scrum.story.manager.default:
        class: NicoB\ScrumBundle\Manager\StoryManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.story.class%]
        
        
        
    nicob.scrum.story.form.type.default:
      class: NicoB\ScrumBundle\Form\Type\StoryFormType
      arguments: [%nicob.scrum.story.class%]
      tags:
          - { name: form.type, alias:nicob.scrum.story.form.type  }
          
    nicob.scrum.story.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [%nicob.scrum.story.form.name%,nicob.scrum.story.form.type ]
    
    nicob.scrum.story.form.handler.default:
      class: NicoB\ScrumBundle\Form\Handler\StoryFormHandler
      arguments: [@nicob.scrum.story.form, @nicob.scrum.story.manager ]
      scope: request
      
        
        
    nicob.scrum.project.form.type.default:
      class: NicoB\ScrumBundle\Form\Type\ProjectFormType
      arguments: [%nicob.scrum.project.class%]
      tags:
          - { name: form.type }
          
    nicob.scrum.project.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [%nicob.scrum.project.form.name%, @nicob.scrum.project.form.type ]
    
    nicob.scrum.project.form.handler.default:
      class: NicoB\ScrumBundle\Form\Handler\ProjectFormHandler
      arguments: [@nicob.scrum.project.form, @request ]
      scope: request
      
        
        
    nicob.scrum.backlog.form.type.default:
      class: NicoB\ScrumBundle\Form\Type\BacklogFormType
      arguments: [%nicob.scrum.backlog.class%]
      tags:
          - { name: form.type }
          
    nicob.scrum.backlog.form:
        factory_method: createNamed
        factory_service: form.factory
        class: Symfony\Component\Form\Form
        arguments: [%nicob.scrum.backlog.form.name%,nicob.scrum.backlog.form.type ]
    
    nicob.scrum.backlog.form.handler.default:
      class: NicoB\ScrumBundle\Form\Handler\BacklogFormHandler
      arguments: [@nicob.scrum.backlog.form, @nicob.scrum.backlog.manager ]
      scope: request     
