services:
    nicob.scrum.backlog.manager.default: 
        class: NicoB\ScrumBundle\Manager\BacklogManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.backlog.class%]

    nicob.scrum.project.manager.default:
        class: NicoB\ScrumBundle\Manager\ProjectManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.project.class%]

    nicob.scrum.sandbox.manager.default:
        class: NicoB\ScrumBundle\Manager\SandboxManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.sandbox.class%]

    nicob.scrum.story.manager.default:
        class: NicoB\ScrumBundle\Manager\StoryManager
        arguments: [@doctrine.orm.entity_manager,%nicob.scrum.story.class%]